**1**. Write the following matrix

```
array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30],
       [ 6, 12, 18, 24, 30, 36]])
```

- 1) using `np.fromfunction` 
- 2) using `numpy` broadcasting
- 3) using `np.einsum`

For 2 and 3 you may use `np.arange(1,7)` as a building block

In [1]:
import numpy as np

In [2]:
np.fromfunction(lambda i,j: (i+1)*(j+1), (6,6), dtype='int')

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30],
       [ 6, 12, 18, 24, 30, 36]])

In [3]:
x = np.arange(1, 7)
x[:,None] @ x[None,:]

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30],
       [ 6, 12, 18, 24, 30, 36]])

In [4]:
np.einsum('i,j', x, x)

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30],
       [ 6, 12, 18, 24, 30, 36]])

**2**. First recreate the DataFrame `df_x` as `df`. Now convert from `df` to `df1` and from `df1` to `df`

In [5]:
import pandas as pd

df_x = pd.read_csv('ex3_q2a.csv')
df1 = pd.read_csv('ex3_q2b.csv')

In [6]:
df_x

n  a  b   c   d
0  x  0  1   2   3
1  y  4  5   6   7
2  z  8  9  10  11

In [7]:
df1

n group  count
0   x     a      0
1   y     a      4
2   z     a      8
3   x     b      1
4   y     b      5
5   z     b      9
6   x     c      2
7   y     c      6
8   z     c     10
9   x     d      3
10  y     d      7
11  z     d     11

In [8]:
df = pd.DataFrame(np.c_[list('xyz'), 
                        np.arange(12).reshape(3,4)],
                  columns=list('nabcd'))
df[list('abcd')]= df.iloc[:, 1:].apply(pd.to_numeric)
df

n  a  b   c   d
0  x  0  1   2   3
1  y  4  5   6   7
2  z  8  9  10  11

In [9]:
df1 = pd.melt(df, id_vars=['n'], var_name='group', value_name='count')
df1

n group  count
0   x     a      0
1   y     a      4
2   z     a      8
3   x     b      1
4   y     b      5
5   z     b      9
6   x     c      2
7   y     c      6
8   z     c     10
9   x     d      3
10  y     d      7
11  z     d     11

In [10]:
df2 = pd.pivot_table(df1, 
                     values='count',
                     columns='group', 
                     index='n').reset_index()
df2.columns.name = None
df2

n  a  b   c   d
0  x  0  1   2   3
1  y  4  5   6   7
2  z  8  9  10  11

**3**. Using **code only**, convert Table 2 on the webpage 'https://www.bls.gov/web/empsit/cesbmart.htm' into the DataFrame `df` shown below. You are **not allowed** to copy and paste the table from the web page.

In [11]:
df = pd.read_csv('ex3_q3.csv')
df

CES Industry Code                    CES Industry Title  As Revised  \
0          20-000000                          Construction      7557.0   
1          31-000000                         Durable goods      7961.0   
2          65-000000         Education and health services     24347.0   
3          55-000000                  Financial activities      8850.0   
4          06-000000                       Goods-producing     20949.0   
5          90-000000                            Government     22774.0   
6          50-000000                           Information      2898.0   
7          70-000000               Leisure and hospitality     16133.0   
8          30-000000                         Manufacturing     12718.0   
9          10-000000                    Mining and logging       674.0   
10         32-000000                      Nondurable goods      4757.0   
11         80-000000                        Other services      5842.0   
12         08-000000             Private service-providing    107117.0   
13         60-000000    Professional and business services     21318.0   
14         42-000000                          Retail trade     15483.6   
15         07-000000                     Service-providing    129891.0   
16         00-000000                         Total nonfarm    150840.0   
17         05-000000                         Total private    128066.0   
18         40-000000  Trade, transportation, and utilities     27729.0   
19         43-000000        Transportation and warehousing      5822.1   
20         44-220000                             Utilities       547.0   
21         41-420000                       Wholesale trade      5876.6   

    As Previously Published  Amount Percent  
0                    7574.0   -17.0    -0.2  
1                    8031.0   -70.0    -0.9  
2                   24408.0   -61.0    -0.3  
3                    8827.0    23.0     0.3  
4                   21086.0  -137.0    -0.7  
5                   22728.0    46.0     0.2  
6                    2888.0    10.0     0.3  
7                   16124.0     9.0     0.1  
8                   12806.0   -88.0    -0.7  
9                     706.0   -32.0    -4.7  
10                   4775.0   -18.0    -0.4  
11                   5850.0    -8.0    -0.1  
12                 107276.0  -159.0    -0.1  
13                  21456.0  -138.0    -0.6  
14                  15586.6  -103.0    -0.7  
15                 130004.0  -113.0    -0.1  
16                 151090.0  -250.0    -0.2  
17                 128362.0  -296.0    -0.2  
18                  27723.0     6.0     (1)  
19                   5668.2   153.9     2.6  
20                    545.9     1.1     0.2  
21                   5922.2   -45.6    -0.8

In [12]:
# url = 'https://www.bls.gov/web/empsit/cesbmart.htm'
url = 'cesbmart.htm'
tables = pd.read_html(url)
df = tables[1]
df.columns = df.columns.droplevel(0)
(
    df.drop(df.tail(1).index).
    sort_values('CES Industry Title').
    reset_index(drop=True)
)

CES Industry Code                    CES Industry Title As Revised  \
0          20-000000                          Construction       7557   
1          31-000000                         Durable goods       7961   
2          65-000000         Education and health services      24347   
3          55-000000                  Financial activities       8850   
4          06-000000                       Goods-producing      20949   
5          90-000000                            Government      22774   
6          50-000000                           Information       2898   
7          70-000000               Leisure and hospitality      16133   
8          30-000000                         Manufacturing      12718   
9          10-000000                    Mining and logging        674   
10         32-000000                      Nondurable goods       4757   
11         80-000000                        Other services       5842   
12         08-000000             Private service-providing     107117   
13         60-000000    Professional and business services      21318   
14         42-000000                          Retail trade    15483.6   
15         07-000000                     Service-providing     129891   
16         00-000000                         Total nonfarm     150840   
17         05-000000                         Total private     128066   
18         40-000000  Trade, transportation, and utilities      27729   
19         43-000000        Transportation and warehousing     5822.1   
20         44-220000                             Utilities      547.0   
21         41-420000                       Wholesale trade     5876.6   

   As Previously Published  Amount Percent  
0                     7574     -17    -0.2  
1                     8031     -70    -0.9  
2                    24408     -61    -0.3  
3                     8827      23     0.3  
4                    21086    -137    -0.7  
5                    22728      46     0.2  
6                     2888      10     0.3  
7                    16124       9     0.1  
8                    12806     -88    -0.7  
9                      706     -32    -4.7  
10                    4775     -18    -0.4  
11                    5850      -8    -0.1  
12                  107276    -159    -0.1  
13                   21456    -138    -0.6  
14                 15586.6  -103.0    -0.7  
15                  130004    -113    -0.1  
16                  151090    -250    -0.2  
17                  128362    -296    -0.2  
18                   27723       6     (1)  
19                  5668.2   153.9     2.6  
20                   545.9     1.1     0.2  
21                  5922.2   -45.6    -0.8

**4**. We have the genetic sequence of a mysterious organism below. Find the **longest** palindrome (sequence that reads the same backwards and forwards) in this 2000-base sequence. If there are ties, show all of them. 

```TTGACCTGGCCGTATGAGTTTGAGCGTGACTGGAGAGTGTCAACCTCTCGTGCTCCTTATTCTGCATCGCACGGATTTGT
AGTCATCATACTTACTATGGACATCCGTAGGGAAGCTAAACTCTGAGTGTTACTGCGGACTAAATATCATATGAAAGTAT
CAATCTACTGGCCCCGCACACGGTACTTAAGGCCATATTCATTCAACGCGCCACAATGTAGATACCAATAATCCGGTGGC
CGTCGATCTTCGGGTCAGGATGGGATAGGGAGTCGTCGTTTGGATACCTACACTCCATCATGGTGAAGTTGGTCAAGCGG
TCAGTAAATGACCACTCCCTTGGGCCGATATGCATCCTCTCGAGAGTAGTAAGTCCATCCGATAGGCTATGGAGAGCTCC
TCCATGTGATCGTTGGGCTGTGTAGTATCAGTTTTTGTTTAAAGTGTGAACGAGCGGGTACAACTGTAAACCGTCCCATG
GTTTGCGGTGGTGCCAGATATAAAGGGTATTCCACTGAACATACTTGTAAACAGCCCATAACCTTCCAACCCTCAATTTG
GCAGTTGGGATTCGGAACCGACCTGGCTCATGGGGGACGCCATATGATCGTCCTACCTCTGGCCGGAATGGTTGTGTTGA
TTAACTAATGTACGGATATGATAGGAAGTGGAAGTGTAGATCAGAGTATATTCACGCTGTCCAAAATTGACTAGGGATCC
ACGCTAGGTACCTATTACGGACCTTCCCAGGTGATTAGTCCGGCGGTAGCCTCCTGCCATTAGCAATTTCAGTCGGCAAT
TATGTGACCGTGCGCTGACATGGCGCTGGGGTATCAGGATGACAGTACTTTAGATTGCGGAGCGTATACTACGGAAGACG
GCATAAGTGGTAGGGGATCCTGAAAGCCACGTAGTAGACCAAGCCACGAAGATTAGGTTACGCCACCGTGCCCAAAAGCG
TTAAGGATCCAAGTAGGGTACTGTCCTCATGTGTAAGGAATCCTCCCCAGGTAAATTTGTAGTCTCCTACAGTGCGTAGG
CCGTGCTTTGGGTATGTACTACGTCCTGCCCTGGCTGGCTACCAGGATGTAGCTTACTGGTTCGTCGTATGAGAGTCCAT
AAGGCCCCAGACAAGGCTTTTTCTATATACAAGTCATAGTTTAATAGGTTTACGGTATGAGTTAGAACTTGCTATAGGGA
CGAACCTGTCGATATAGGGTGCGGATCGAAGTTATAATTGTGTCCTATAGGGACTCCTACAATATCCTAGCCTAACCAAC
CACGCTACCCCTATCAGGCGTAGACTTGGTGACCCTGACTATCAGCTTAGTATGGACCTCTCAACGCATGCCCTATAATG
GCAAAAGAGGCCATGTATTCGGCCTATCTCAAGCAACACACAAGATGGTCGCTCCTCGGGCGGAACGTCCTCCGACATAA
AATTGCGGCTCGGCCGGACAAAGGAAGGTGAGCAAAGCACAGGGCAACTGCTAATAGGTTTAGCGAGGAGACAATCGGAC
ACCTGGTAAGGCACATTTCACATTTCAGAGATCACCACTCTACCTGTGCACAACCTAATTGACGGTGGGTCTACAGCTAC
AATCGAGGATCAAACGCTAGGCAACGGCGTGAGTCCAGGCCCACCCGCCACATCGATAGGCACGAGTCTATTGCCCCCCG
TGAGCAAATCAGCGTACGTCGGAACGTCGCTTATCCGAATCAAAGCACTTTGCGGGGTCTCGATTGCCGCAGCGACCTTA
GACACGAGTTGAATACAGTACTAGAGTGTTAAAGCACCACCAGAAGCTTACTACACGGTCGAGTCTTTTTGTTTATAGGA
TCGTTGGGATCATACTGATTTAGGCACCCGCGAACAAATCATTACGTTCGCACAGCCCCTGGACGCTTGTTTACGGCCAA
CGGTTAGTTCTCCCAATCTGACTAAAGAGGGGTTCATGGATAAATTTGCATGTACGTTTAATAATAGGTCTGCTTGGAAG
```

In [13]:
dna = ''.join("""TTGACCTGGCCGTATGAGTTTGAGCGTGACTGGAGAGTGTCAACCTCTCGTGCTCCTTATTCTGCATCGCACGGATTTGT
AGTCATCATACTTACTATGGACATCCGTAGGGAAGCTAAACTCTGAGTGTTACTGCGGACTAAATATCATATGAAAGTAT
CAATCTACTGGCCCCGCACACGGTACTTAAGGCCATATTCATTCAACGCGCCACAATGTAGATACCAATAATCCGGTGGC
CGTCGATCTTCGGGTCAGGATGGGATAGGGAGTCGTCGTTTGGATACCTACACTCCATCATGGTGAAGTTGGTCAAGCGG
TCAGTAAATGACCACTCCCTTGGGCCGATATGCATCCTCTCGAGAGTAGTAAGTCCATCCGATAGGCTATGGAGAGCTCC
TCCATGTGATCGTTGGGCTGTGTAGTATCAGTTTTTGTTTAAAGTGTGAACGAGCGGGTACAACTGTAAACCGTCCCATG
GTTTGCGGTGGTGCCAGATATAAAGGGTATTCCACTGAACATACTTGTAAACAGCCCATAACCTTCCAACCCTCAATTTG
GCAGTTGGGATTCGGAACCGACCTGGCTCATGGGGGACGCCATATGATCGTCCTACCTCTGGCCGGAATGGTTGTGTTGA
TTAACTAATGTACGGATATGATAGGAAGTGGAAGTGTAGATCAGAGTATATTCACGCTGTCCAAAATTGACTAGGGATCC
ACGCTAGGTACCTATTACGGACCTTCCCAGGTGATTAGTCCGGCGGTAGCCTCCTGCCATTAGCAATTTCAGTCGGCAAT
TATGTGACCGTGCGCTGACATGGCGCTGGGGTATCAGGATGACAGTACTTTAGATTGCGGAGCGTATACTACGGAAGACG
GCATAAGTGGTAGGGGATCCTGAAAGCCACGTAGTAGACCAAGCCACGAAGATTAGGTTACGCCACCGTGCCCAAAAGCG
TTAAGGATCCAAGTAGGGTACTGTCCTCATGTGTAAGGAATCCTCCCCAGGTAAATTTGTAGTCTCCTACAGTGCGTAGG
CCGTGCTTTGGGTATGTACTACGTCCTGCCCTGGCTGGCTACCAGGATGTAGCTTACTGGTTCGTCGTATGAGAGTCCAT
AAGGCCCCAGACAAGGCTTTTTCTATATACAAGTCATAGTTTAATAGGTTTACGGTATGAGTTAGAACTTGCTATAGGGA
CGAACCTGTCGATATAGGGTGCGGATCGAAGTTATAATTGTGTCCTATAGGGACTCCTACAATATCCTAGCCTAACCAAC
CACGCTACCCCTATCAGGCGTAGACTTGGTGACCCTGACTATCAGCTTAGTATGGACCTCTCAACGCATGCCCTATAATG
GCAAAAGAGGCCATGTATTCGGCCTATCTCAAGCAACACACAAGATGGTCGCTCCTCGGGCGGAACGTCCTCCGACATAA
AATTGCGGCTCGGCCGGACAAAGGAAGGTGAGCAAAGCACAGGGCAACTGCTAATAGGTTTAGCGAGGAGACAATCGGAC
ACCTGGTAAGGCACATTTCACATTTCAGAGATCACCACTCTACCTGTGCACAACCTAATTGACGGTGGGTCTACAGCTAC
AATCGAGGATCAAACGCTAGGCAACGGCGTGAGTCCAGGCCCACCCGCCACATCGATAGGCACGAGTCTATTGCCCCCCG
TGAGCAAATCAGCGTACGTCGGAACGTCGCTTATCCGAATCAAAGCACTTTGCGGGGTCTCGATTGCCGCAGCGACCTTA
GACACGAGTTGAATACAGTACTAGAGTGTTAAAGCACCACCAGAAGCTTACTACACGGTCGAGTCTTTTTGTTTATAGGA
TCGTTGGGATCATACTGATTTAGGCACCCGCGAACAAATCATTACGTTCGCACAGCCCCTGGACGCTTGTTTACGGCCAA
CGGTTAGTTCTCCCAATCTGACTAAAGAGGGGTTCATGGATAAATTTGCATGTACGTTTAATAATAGGTCTGCTTGGAAG
""".split())

In [14]:
n = len(dna)
seqs = []
for size in range(n, 1, -1):
    for start in range(n-size+1):
        stop = start + size
        seq = dna[start:stop]
        if seq == seq[::-1]:
            seqs.append(seq)
    if seqs:
        break
        
seqs

['AATTTGCATGTACGTTTAA']

**5**. Convert `df` to `df_end`.

In [15]:
df = pd.read_csv('ex3_q3.csv')
df

CES Industry Code                    CES Industry Title  As Revised  \
0          20-000000                          Construction      7557.0   
1          31-000000                         Durable goods      7961.0   
2          65-000000         Education and health services     24347.0   
3          55-000000                  Financial activities      8850.0   
4          06-000000                       Goods-producing     20949.0   
5          90-000000                            Government     22774.0   
6          50-000000                           Information      2898.0   
7          70-000000               Leisure and hospitality     16133.0   
8          30-000000                         Manufacturing     12718.0   
9          10-000000                    Mining and logging       674.0   
10         32-000000                      Nondurable goods      4757.0   
11         80-000000                        Other services      5842.0   
12         08-000000             Private service-providing    107117.0   
13         60-000000    Professional and business services     21318.0   
14         42-000000                          Retail trade     15483.6   
15         07-000000                     Service-providing    129891.0   
16         00-000000                         Total nonfarm    150840.0   
17         05-000000                         Total private    128066.0   
18         40-000000  Trade, transportation, and utilities     27729.0   
19         43-000000        Transportation and warehousing      5822.1   
20         44-220000                             Utilities       547.0   
21         41-420000                       Wholesale trade      5876.6   

    As Previously Published  Amount Percent  
0                    7574.0   -17.0    -0.2  
1                    8031.0   -70.0    -0.9  
2                   24408.0   -61.0    -0.3  
3                    8827.0    23.0     0.3  
4                   21086.0  -137.0    -0.7  
5                   22728.0    46.0     0.2  
6                    2888.0    10.0     0.3  
7                   16124.0     9.0     0.1  
8                   12806.0   -88.0    -0.7  
9                     706.0   -32.0    -4.7  
10                   4775.0   -18.0    -0.4  
11                   5850.0    -8.0    -0.1  
12                 107276.0  -159.0    -0.1  
13                  21456.0  -138.0    -0.6  
14                  15586.6  -103.0    -0.7  
15                 130004.0  -113.0    -0.1  
16                 151090.0  -250.0    -0.2  
17                 128362.0  -296.0    -0.2  
18                  27723.0     6.0     (1)  
19                   5668.2   153.9     2.6  
20                    545.9     1.1     0.2  
21                   5922.2   -45.6    -0.8

In [16]:
df_end = pd.read_csv('ex3_q5.csv')
df_end

Industry Group                    CES Industry Title  As Revised  \
0            Good                         Durable goods      7961.0   
1            Good                       Goods-producing     20949.0   
2            Good                      Nondurable goods      4757.0   
3         Service         Education and health services     24347.0   
4         Service                        Other services      5842.0   
5         Service             Private service-providing    107117.0   
6         Service    Professional and business services     21318.0   
7         Service                     Service-providing    129891.0   
8           Trade                          Retail trade     15483.6   
9           Trade  Trade, transportation, and utilities     27729.0   
10          Trade                       Wholesale trade      5876.6   

    As Previously Published  Amount Percent  
0                    8031.0   -70.0    -0.9  
1                   21086.0  -137.0    -0.7  
2                    4775.0   -18.0    -0.4  
3                   24408.0   -61.0    -0.3  
4                    5850.0    -8.0    -0.1  
5                  107276.0  -159.0    -0.1  
6                   21456.0  -138.0    -0.6  
7                  130004.0  -113.0    -0.1  
8                   15586.6  -103.0    -0.7  
9                   27723.0     6.0     (1)  
10                   5922.2   -45.6    -0.8

In [17]:
import re

df['Industry Group'] = (
    df['CES Industry Title'].
    str.extract('(good|trade|service)', flags=re.IGNORECASE, expand=False).
    str.title()
)
df = (df.
 dropna(subset=['Industry Group']).
 sort_values('Industry Group')
)
df = (
    df[df.columns[-1:].tolist() + df.columns[1:-1].tolist()].
    reset_index(drop=True)
)
df

Industry Group                    CES Industry Title  As Revised  \
0            Good                         Durable goods      7961.0   
1            Good                       Goods-producing     20949.0   
2            Good                      Nondurable goods      4757.0   
3         Service         Education and health services     24347.0   
4         Service                        Other services      5842.0   
5         Service             Private service-providing    107117.0   
6         Service    Professional and business services     21318.0   
7         Service                     Service-providing    129891.0   
8           Trade                          Retail trade     15483.6   
9           Trade  Trade, transportation, and utilities     27729.0   
10          Trade                       Wholesale trade      5876.6   

    As Previously Published  Amount Percent  
0                    8031.0   -70.0    -0.9  
1                   21086.0  -137.0    -0.7  
2                    4775.0   -18.0    -0.4  
3                   24408.0   -61.0    -0.3  
4                    5850.0    -8.0    -0.1  
5                  107276.0  -159.0    -0.1  
6                   21456.0  -138.0    -0.6  
7                  130004.0  -113.0    -0.1  
8                   15586.6  -103.0    -0.7  
9                   27723.0     6.0     (1)  
10                   5922.2   -45.6    -0.8