# BIOS 823 Midterm Exam

- This is an open book exam
- There are 4 questions worth 25 points each
- There is 1 bonus question worth 10 points
- The maximum number of points is 100
- Points will be deducted for poor coding practices
- Points will be deducted for inefficient code
- The exam will be for 90 minutes only 4:45 - 6:15 PM

Please print your name below to indicate that you agree to follow the **Duke Honor Code**

NAME:

If you do not print your name, it is an automatic 25 point deduction.

**1**. 25 points

- Create the following `numpy` array $A$ using `fromfunction` (10 points)
    - If you cannot create the matrix, load it using `A = np.load(ex1.npy)`. You will not receive credit for the first part but can still receive credit for the other parts.
```
array([[0, 1, 2, 3, 4],
       [1, 0, 2, 3, 4],
       [2, 2, 0, 3, 4],
       [3, 3, 3, 0, 4],
       [4, 4, 4, 4, 0]])
```

- Transform $A$ into $B$ such that all *rows* of $B$ have length 1. Check your solution. (15 points)

In [1]:
import numpy as np

In [2]:
A = np.fromfunction(lambda i, j: np.where(i==j, 0, np.where(i>j, i, j)), (5,5), dtype='int')

In [3]:
A

array([[0, 1, 2, 3, 4],
       [1, 0, 2, 3, 4],
       [2, 2, 0, 3, 4],
       [3, 3, 3, 0, 4],
       [4, 4, 4, 4, 0]])

In [4]:
A

array([[0, 1, 2, 3, 4],
       [1, 0, 2, 3, 4],
       [2, 2, 0, 3, 4],
       [3, 3, 3, 0, 4],
       [4, 4, 4, 4, 0]])

In [5]:
B = A / np.sqrt((A**2).sum(axis=1))[:, None]

In [6]:
B

array([[0.        , 0.18257419, 0.36514837, 0.54772256, 0.73029674],
       [0.18257419, 0.        , 0.36514837, 0.54772256, 0.73029674],
       [0.34815531, 0.34815531, 0.        , 0.52223297, 0.69631062],
       [0.45749571, 0.45749571, 0.45749571, 0.        , 0.60999428],
       [0.5       , 0.5       , 0.5       , 0.5       , 0.        ]])

In [7]:
(B**2).sum(axis=1)

array([1., 1., 1., 1., 1.])

**2**. 25 points

For this question, you can assume that the input is an integer.

- Count the number of **palindromic** prime numbers less than 1,000,000 (10 points)
    - Single digit primes are automatically palindromic.
- Find all positive integers under 10,000 with the property that the integer is equal to the sum of its proper divisors. A proper divisor includes 1 but not the number itself. For example, one such integer is 6, since 6 = 1+2+3 (15 points)

In [27]:
def is_prime(n):
    if n==2:
        return True
    if (n < 2) or (n%2 == 0):
        return False
    for i in range(3, 1+int(np.sqrt(n)), 2):
        if n % i == 0:
            return False
    return True

In [32]:
len([i for i in range(1, 1_000_000) if is_prime(i) and str(i) ==  str(i)[::-1]])

113

In [10]:
def divisors(n):
    return [i for i in range(1, n) if n % i == 0]

In [11]:
[i for i in range(1, 10000) if i == sum(divisors(i))]

[6, 28, 496, 8128]

**3**. 25 points

You are given this string

```
AAAACCATCGGCTGTAGCCGACTCGCACTATCCAGGGGTAGTAACTGAACTATTGAGTCCCCAGCGTTATATGTGGTTTG
CGAGATAACGCTGTTACGAGTACTGCCAGATACAACTACGCAATTCCGCGCAGGGTCATTAATGATTACCGTCTAGATAG
GAGACACTAGTTAATTACTAAACCATTTCTATCGTCATAAGCGTACAGGTTCAGGGTATTGGGCGCATGTAGGATAGGCT
TATTGCCCTCCACAGGGACTCTTCCGCTAATTGTATCATAAAACAGACTATGGCCTCCTGAGTAGACCACTGAGAGTGGT
CAAGTAATGAGCAATTTAAGATGATTTGGAAGGCTCAAGCTTTACGGATTTGGCCGGGACCCTGAAGTCAGGGCGCACGG
GCCTATTACTAATCCCATTCCGCATGCAACATACTGCTCATCACCGTTTATAGCTTGAACTTGTAGATGCCCGGGCACTG
CGCGACGCTCTCCGGTGGCTTCTTTCTTTTCCGTTCCGCGCTTCAGACCCAACTAATAGGCACTCAAAGGTGGGAGGGCC
GATGACCACCACGCATAGAGTGCACGTCATCTATGATCCGACGACTTGCCACCTGTCTACTTTAGAGTTCAAACATTCAG
GCACTGCTGACCCGTATAGCAAGCATAAATTAGCGCAACGGGCGGCGGTGTATGCCTTTAACATTCGAGCTATACTCAGT
CGGATAGGCTCTCGTCACTACTGGCCGGGGTCGAAAGTTGACACGGATTAGTGGATCCCTGTTTTGGGTTTAGTTTCCTC
```

This should be considered as a *single* sequence of length 800, not 10 sequences of length 80.

- Use a regular expression to find the number of sequences that begin and end with `A` and have length between 6 and 8 (inclusive). For full credit, use a non-greedy regular expression. (10 points)
- Print the 10 most common substrings of length 3 with their counts (15 points)

In [12]:
s = '''AAAACCATCGGCTGTAGCCGACTCGCACTATCCAGGGGTAGTAACTGAACTATTGAGTCCCCAGCGTTATATGTGGTTTG
CGAGATAACGCTGTTACGAGTACTGCCAGATACAACTACGCAATTCCGCGCAGGGTCATTAATGATTACCGTCTAGATAG
GAGACACTAGTTAATTACTAAACCATTTCTATCGTCATAAGCGTACAGGTTCAGGGTATTGGGCGCATGTAGGATAGGCT
TATTGCCCTCCACAGGGACTCTTCCGCTAATTGTATCATAAAACAGACTATGGCCTCCTGAGTAGACCACTGAGAGTGGT
CAAGTAATGAGCAATTTAAGATGATTTGGAAGGCTCAAGCTTTACGGATTTGGCCGGGACCCTGAAGTCAGGGCGCACGG
GCCTATTACTAATCCCATTCCGCATGCAACATACTGCTCATCACCGTTTATAGCTTGAACTTGTAGATGCCCGGGCACTG
CGCGACGCTCTCCGGTGGCTTCTTTCTTTTCCGTTCCGCGCTTCAGACCCAACTAATAGGCACTCAAAGGTGGGAGGGCC
GATGACCACCACGCATAGAGTGCACGTCATCTATGATCCGACGACTTGCCACCTGTCTACTTTAGAGTTCAAACATTCAG
GCACTGCTGACCCGTATAGCAAGCATAAATTAGCGCAACGGGCGGCGGTGTATGCCTTTAACATTCGAGCTATACTCAGT
CGGATAGGCTCTCGTCACTACTGGCCGGGGTCGAAAGTTGACACGGATTAGTGGATCCCTGTTTTGGGTTTAGTTTCCTC'''
s = ''.join(s.split())

In [13]:
import re

In [14]:
len(re.findall('A.{4,6}?A', s))

60

In [15]:
from collections import Counter

triplets = [''.join(t) for t in list(zip(s, s[1:], s[2:]))]
c = Counter(triplets)
c.most_common(10)

[('ACT', 23),
 ('TAG', 18),
 ('ATT', 18),
 ('GGC', 17),
 ('GCA', 16),
 ('CTA', 16),
 ('GGG', 16),
 ('TTA', 16),
 ('TTT', 16),
 ('TCA', 16)]

**4**. 25 points

- Read the `feather` file `ex4.feather` into a `pandas` DataFrame `df1`. 
    - Note this is a 1,000,000 by 100 DataFrame
- Create a new DataFrame `df2` from the 10 columns that have the highest mean value (5 points)
- Create a new DataFrame `df3` from the 10 columns that have the suffix 07 (5 points)
- Create a new DataFraem `df4` containing the min, max and average of all columns that begin with the same letter . The min, max, and average should be 3 separate rows, and the columns will be `A`, `B`, etc (15 points)
    - The total time taken for the code should not take more than 1 minute to complete

Note: You are **not** allowed to specify any column names such as `B05` directly in these questions. 
- Doing so will result in a deduction of 10 points from your final score

Suggestion: You might want to work with a subset of the data until you are sure your code is correct and efficient. Otherwise you might have to wait a long time.

In [16]:
import pandas as pd

In [17]:
df1 = pd.read_feather('ex4.feather')

In [18]:
df1.sample(5)

A01  A02  A03  A04  A05  A06  A07  A08  A09  A10  ...  J01  J02  J03  \
352982   15   61   83    4    7   30   22   69   48   58  ...    5   83   59   
164505   73   73   11   23   99   63   72   33   69   94  ...   47   27   49   
579420   28   49   26   75   25   73   19   45   85   96  ...   53   28   65   
591730   74    5   33   48   13   82   23   78   80   73  ...   44   47   26   
971481   67   60   23   56   33   60   28   29   65   28  ...   74   59    2   

        J04  J05  J06  J07  J08  J09  J10  
352982   37   55   79    0   91   86   65  
164505    0   23   43   46   96   63   43  
579420   58   51   74   49   71   90   85  
591730    0   24   58   11   44   20   57  
971481   93   51   50   79   46    3   48  

[5 rows x 100 columns]

In [19]:
df1.shape

(1000000, 100)

In [20]:
m = df1.mean(axis=0)
df2 = df1[m.sort_values(ascending=False)[:10].index]
df2.head()

H04  H02  D05  J09  C07  I10  E01  A10  E10  I09
0   36   94   98   28   25   83   11    1    7   60
1   54   78   85   85   34   79   31   35   45    0
2   15   88   51   37   70   28   82   59   36   87
3   62    1   41   75   69   65   61    6   78   80
4   14   40   19   60    0   21   98    4   44   11

In [21]:
df3 = df1[[c for c in df1.columns if c.endswith('07')]]
df3.head()

A07  B07  C07  D07  E07  F07  G07  H07  I07  J07
0   98   63   25   71   93   83   76    4   63   12
1   40   68   34   98   65   62   97   61   66   29
2   88   85   70    4   19   51   47   36   17   64
3   48    0   69   25   95   23   76   13    6   74
4   99   12    0   78   49   33   84   67   43   84

In [22]:
df4a = pd.melt(df1, id_vars=[])

In [23]:
df4b = df4a.assign(ch=df4a.variable.str[:1]).drop('variable', axis=1)

In [24]:
df4 = df4b.groupby('ch').agg(['min', 'max', 'mean'])

In [25]:
df4.T

ch                  A          B          C          D          E         F  \
value min    0.000000   0.000000   0.000000   0.000000   0.000000   0.00000   
      max   99.000000  99.000000  99.000000  99.000000  99.000000  99.00000   
      mean  49.497658  49.488565  49.499336  49.490343  49.506956  49.50521   

ch                  G          H          I          J  
value min    0.000000   0.000000   0.000000   0.000000  
      max   99.000000  99.000000  99.000000  99.000000  
      mean  49.483119  49.520096  49.508273  49.490887

**5**. Bonus question - 10 points

Do this only if you have time.

Connect to the `Chinnok.db` SQLite3 database. Find the names of the music tracks bought by the customer with the highest total amount in a single invoice.

In [1]:
%load_ext sql

In [2]:
%sql sqlite:///Chinook.db

In [3]:
%%sql

SELECT Track.Name
FROM InvoiceLine, Invoice, Customer, Track
WHERE Invoice.CustomerId = Customer.CustomerId
AND InvoiceLine.InvoiceId = Invoice.InvoiceId
AND InvoiceLine.TrackId = Track.TrackId
AND Customer.CustomerId IN (
    SELECT Invoice.CustomerId
    FROM Invoice
    ORDER BY Total DESC
    LIMIT 1
)

 * sqlite:///Chinook.db
Done.


[('When You Gonna Learn (Digeridoo)',),
 ("Whatever It Is, I Just Can't Stop",),
 ('Black Capricorn Day',),
 ('Were Do We Go From Here',),
 ('Light Years',),
 ('Morning Glory',),
 ('Get What You Need',),
 ('Take It Or Leave It',),
 ('Can You See Me',),
 ('How The West Was Won And Where It Got Us',),
 ('The Wake-Up Bomb',),
 ('Heartland',),
 ('The Star Spangled Banner',),
 ('All I Want Is You',),
 ("New Year's Day",),
 ('My Time After Awhile',),
 ('Prenda Minha',),
 ('Texto "Verdade Tropical"',),
 ('Carolina',),
 ('Linha Do Equador',),
 ('Vida Boa',),
 ('Revolta Olodum',),
 ('Winterlong',),
 ('Blissed & Gone',),
 ('Insensível',),
 ('Collaborators',),
 ('The Woman King',),
 ('One Giant Leap',),
 ('The Fix',),
 ('Man of Science, Man of Faith (Premiere)',),
 ('Walkabout',),
 ('The Moth',),
 ('Stranger In a Strange Land',),
 ('Par Avion',),
 ('Outlaws',),
 ('Deus Ex Machina',),
 ('Live Together, Die Alone, Pt. 1',),
 ('So Cruel',)]